Fixed Syntax Error

diff --git a/config b/config
--- a/config
+++ b/config
@@ -1,30 +1,32 @@
-#!/system/bin/sh
+#!/bin/sh
 
-LOCAL_REPO_NAME="https://github.com/Linus-Ishigami/Team-Fortress/"
 LOCAL_COMMIT_ID="$(getprop persist.sys.fortress.ccid)"
 DEVICE_PREFIX="$(getprop persist.sys.fortress.model)"
 DEVICE_INCREMENTAL="$(getprop ro.system.build.version.incremental)"
-CURRENT_COMMIT_ID="$(wget -qO "/sdcard/.ota_config" "https://github.com/Linus-Ishigami/Team-Fortress/${DEVICE_PREFIX}/${DEVICE_INCREMENTAL}/config" && cat /sdcard/.ota_config)"
+LAST_COMMIT_ID="$(wget -qO "/sdcard/.ota_config" "https://github.com/Linus-Ishigami/Team-Fortress/${DEVICE_PREFIX}/${DEVICE_INCREMENTAL}/config" && cat /sdcard/.ota_config)"
 BOOL="$(wget -qO "/sdcard/.ota_status" "https://github.com/Linus-Ishigami/Team-Fortress/${DEVICE_PREFIX}/${DEVICE_INCREMENTAL}/status" && cat /sdcard/.ota_status)"
 
 nig() {
-if [[ $(getprop persist.sys.locale) == "en-US" ]]; then
+if [ $(getprop persist.sys.locale) == "en-US" ]; then
 	true
-elif [[ $(getprop persist.sys.locale) == "pt-BR" ]]; then
+elif [ $(getprop persist.sys.locale) == "pt-BR" ]; then
 	false
+else
+    true	# ~ luna bennett
 fi
 }
 
 do_the_requirements() {
-    wget -qO "/data/ota/.${RANDOMSEED}.zip" "https://github.com/Linus-Ishigami/Team-Fortress/pkgs/${CURRENT_COMMIT_ID}"
-	cat >> command << EOF
-	--update_package "/data/ota/${RANDOMSEED}.zip"
-	EOF 
+    wget -qO "/data/ota/.$(head -c 16 /dev/urandom | xxd -p).zip" "https://github.com/Linus-Ishigami/Team-Fortress/pkgs/${DEVICE_PREFIX}_${LAST_COMMIT_ID}"
+	#cat >> command << EOF
+	echo "--update_package \"/data/ota/${RANDOMSEED}.zip\" " > ./command
+	#EOF 
 	rm /sdcard/.ota_config
 	rm /sdcard/.ota_status
 	cp command /cache/recovery/command && chown 0 /cache/recovery/command && chgrp 0 /cache/recovery/command && chmod 0644 /cache/recovery/command
-    nig && printf " - the update requires a reboot, do you want to reboot now? " && read fi || printf " - a atualização requer uma reinicialização, deseja reiniciar agora?" && read fi
-	case "$fi" in
+    nig && printf " - the update requires a reboot, do you want to reboot now? " && read f
+	nig || printf " - a atualização requer uma reinicialização, deseja reiniciar agora?" && read f
+	case "$f" in
 		y*|Y*)
 		setprop sys.powerctl reboot,recovery
 		;;
@@ -38,42 +40,58 @@ do_the_requirements() {
 
 clear
 if [ "$(id -u)" -ne "0" ]; then
-nig && "Root Privilages were required." || "Privilégios de root eram necessários"
+nig && echo "Root Privilages were required."
+nig || echo "Privilégios de root eram necessários"
 exit
+fi
+
+if [ ! "$(ls $PREFIX/bin | grep -q "termux")" ]; then
+: ' termux user, ignore em'
+clear
+else
+nig && echo "Termux is required to install updates!"
+nig || echo "Termux é necessário para instalar atualizações!"
+exit 0
 fi
 
 # let's print our "COOL" banner ig.
 echo "										 "
-echo "   _____          _                     "
-echo "  |  ___|__  _ __| |_ _ __ ___  ___ ___ "
-echo "  | |_ / _ \|  __| __|  __/ _ \/ __/ __|"
-echo " |  _| (_) | |  | |_| | |  __/\__ \__ \"
-echo "|_|  \___/|_|   \__|_|  \___||___/___/"
+echo "#######                                                 "
+echo "#        ####  #####  ##### #####  ######  ####   ####  "
+echo "#       #    # #    #   #   #    # #      #      #      "
+echo "#####   #    # #    #   #   #    # #####   ####   ####  "
+echo "#       #    # #####    #   #####  #           #      # "
+echo "#       #    # #   #    #   #   #  #      #    # #    # "
+echo "#        ####  #    #   #   #    # ######  ####   ####  "
 echo "                                      "
 echo ""
 
 # let's check if the current id was the same or not.
-$BOOL || nig && "No Changes were made to the rom, please try after a day!" || "Nenhuma alteração foi feita na rom, tente depois de um dia!" 
+$BOOL || nig && echo "No Changes were made to the rom, please try after a day!" 
+$BOOL || nig || echo "Nenhuma alteração foi feita na rom, tente depois de um dia!" 
 $BOOL || exit 0
 
-if [ "${CURRENT_COMMIT_ID}" ==! "${LOCAL_COMMIT_ID}" ]; then
+if [ "${LAST_COMMIT_ID}" -ne "${LOCAL_COMMIT_ID}" ]; then
 #nig && printf " - Updates were found, showing changelogs.." && am start -a android.intent.action.VIEW -d "https://github.com/Linus-Ishigami/Team-Fortress/changelogs/oh_walla_i_hate_nigga.log" && sleep 5
-nig && printf " - Do you want to update the rom?" && read fi || printf " - Deseja atualizar o software?"
+nig && printf " - Do you want to update the rom?" && read f || printf " - Deseja atualizar o software?" && read f
 
 # SWITCH Operator :
-case "$fi" in
+case "$f" in
 y*|Y*)
 do_the_requirements
 ;;
 
 *)
-nig && "Thank you!" || "Obrigado!"
+nig && echo "Thank you!" 
+nig || echo "Obrigado!"
 exit 0
 ;;
 
 esac
 
 else 
-nig && "Okay!" || "OK!"
+nig && echo "Okay!" 
+nig || echo "OK\!"
 exit 0
 fi
+;;
